### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
# image_max_pixels: 262144
# video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora # full
lora_rank: 8 # comment out if "full"
lora_target: all # comment out if "full"
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: clevr_r1
template: qwen2_vl
cutoff_len: 16384
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: ckpts/qwen25_vl-3b/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 540000000
resume_from_checkpoint: null

report_to: wandb
run_name: qwen25_vl-3b_sft_clevr_r1

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
